{{- if and (not .Values.externalSecret.enabled) .Values.secrets.create -}}
# Dev-only inline secret. Prod uses the ExternalSecret (OCI Vault) instead.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gts.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gts.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end -}}
