{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gts.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gts.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end -}}
